/* Generated By:JavaCC: Do not edit this line. ParserPrologConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserPrologConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ARROW = 5;
  /** RegularExpression Id. */
  int Symbol1 = 6;
  /** RegularExpression Id. */
  int CH = 7;
  /** RegularExpression Id. */
  int QUOTED = 8;
  /** RegularExpression Id. */
  int INT = 9;
  /** RegularExpression Id. */
  int DIGIT = 10;
  /** RegularExpression Id. */
  int UPPER = 11;
  /** RegularExpression Id. */
  int LOWER = 12;
  /** RegularExpression Id. */
  int VAR = 13;
  /** RegularExpression Id. */
  int ATOM = 14;
  /** RegularExpression Id. */
  int EXCLAMATION = 15;
  /** RegularExpression Id. */
  int fail = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\":-\"",
    "\"< >\"",
    "<CH>",
    "<QUOTED>",
    "<INT>",
    "<DIGIT>",
    "<UPPER>",
    "<LOWER>",
    "<VAR>",
    "<ATOM>",
    "\"!\"",
    "\",fail\"",
    "\",\"",
    "\",fail.\"",
    "\".\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"|\"",
    "\"]\"",
    "\"call(\"",
    "\"=..\"",
    "\":=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
  };

}
